# Generated by Django 3.1.1 on 2024-01-19 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
                ('img', models.TextField()),
                ('dog_name', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=140)),
                ('body_text', models.TextField()),
                ('breed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotapp.dogbreed')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotapp.city')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotapp.user')),
            ],
        ),
    ]
